Bug/manual install issue#722
TencentBlueKing/bk-nodeman pull request #1016
Opened 2022-08-22 09:44 UTC by ladymamawang

2022-08-22 10:55 UTC, ladymamawang commented
忘记改单测了，优先处理

2022-08-23 03:04 UTC, ZhuoZhuoCrayon approved these changes

2022-08-23 03:04 UTC, ZhuoZhuoCrayon commented on apps/node_man/constants.py
> +class WinInstallTools(EnhanceEnum):
多余的常量，详见 `constants.AgentWindowsDependencies`

2022-08-23 03:04 UTC, ZhuoZhuoCrayon commented on apps/node_man/constants.py
> +class ManualInstallDisplayType:
多余的常量，详见 `CommonExecutionSolutionStepType`

2022-08-23 03:04 UTC, ZhuoZhuoCrayon commented on apps/node_man/tests/test_handlers/test_job.py
> +        JobHandler().list({"page": 1, "pagesize": 10, "job_type": constants.JOB_TUPLE}, "admin")
👍 主动改了 `const`

2022-08-23 03:04 UTC, ZhuoZhuoCrayon commented on apps/node_man/views/__init__.py
> +def tools_download(request):
这个方法在 apps/node_man/tests/test_views 下补充单元测试

2022-08-23 03:04 UTC, ZhuoZhuoCrayon commented on frontend/src/views/task/task-detail-slider.vue
> +    element.setAttribute('href', `tools/download/?file_name=${name}`);
用这个 toolsDownload

2022-08-23 03:04 UTC, ZhuoZhuoCrayon commented on apps/backend/views.py
> +    storage = get_storage()
是不是多了一行代码？

2022-08-23 03:04 UTC, ZhuoZhuoCrayon reviewed
回滚

2022-08-23 03:05 UTC, ZhuoZhuoCrayon requested changes
回滚

2022-08-25 07:10 UTC, closed without merging