optimization: 插件操作前置下发更新依赖脚本 (closed #471)
TencentBlueKing/bk-nodeman pull request #1055
Opened 2022-09-09 14:35 UTC by ladymamawang

2022-11-02 12:41 UTC, ZhuoZhuoCrayon approved these changes

2022-11-02 12:41 UTC, ZhuoZhuoCrayon commented on apps/backend/components/collections/plugin.py
> +        return self.get_file_target_path
`return self.get_file_target_path` -> `return self.get_file_target_path(xxxxx)` ?

2022-11-02 12:41 UTC, ZhuoZhuoCrayon commented on apps/backend/components/collections/plugin.py
> +class TransferScriptService(PluginTransferFileService, JobExecuteScriptService):
继承文件分发 / 脚本执行的能力，但最终执行是通过同一个 `_execute` 去构造 JOB 任务的，依照 MRO 类方法继承顺序规则，最终这个类的能力是「传输文件」，达不到预期的先下发文件，再对文件赋权的能力。

MRO：https://www.educative.io/answers/what-is-mro-in-python

综上，在一个原子里是做不到下发脚本、脚本赋权两个操作的

2022-11-02 12:49 UTC, ZhuoZhuoCrayon requested changes
撤回 Approve

2022-11-02 13:26 UTC, ZhuoZhuoCrayon commented on apps/backend/components/collections/plugin.py
> +            super(JobTransferFileService, self)._execute(data, parent_data, common_data)
请求是“异步”的，看似串行的请求，不能保证在作业平台是“串行”的
也就是说，可能存在先对脚本授权，再下发脚本的情况

2022-11-02 13:26 UTC, ZhuoZhuoCrayon commented on apps/backend/components/collections/plugin.py
> +        return process_status.setup_path
第三方插件的启停脚本是自定义的，所以这里的目标路径直接指定：`$GSE_HOME/plugins/bin`
具体的取用方式：
```
agent_config = self.get_agent_config_by_process_status(process_status, common_data)
file_target_path = agent_config["temp_path"]
```

2022-11-15 02:39 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-nodeman?pullRequest=1055) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-nodeman?pullRequest=1055) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-nodeman?pullRequest=1055) it.</sub>

2022-11-22 10:33 UTC, ZhuoZhuoCrayon approved these changes

2022-11-22 10:33 UTC, ZhuoZhuoCrayon commented on apps/backend/plugin/manager.py
> +    def init_porc_script(self):
porc 单词是不是拼错了

2022-11-22 10:33 UTC, ZhuoZhuoCrayon commented on apps/backend/subscription/steps/plugin.py
> +            plugin_manager.transfer_script(op_types=[constants.GseOpType.STOP]),
只有 Main 开头的 Action 才需要前置下发

2022-11-22 10:33 UTC, merged