feature: 支持切换 Proxy 与 P-Agent 的通信 IP (close #1352)
TencentBlueKing/bk-nodeman pull request #1353
Opened 2022-12-22 03:04 UTC by ladymamawang

2022-12-22 07:19 UTC, ZhuoZhuoCrayon commented on apps/node_man/models.py
> +        proxy_communication_ip_field: str = getattr(settings, "PROXY_COMMUNICATION_IP_FIELD", "inner_ip")
这里可以直接取值 `settings.PROXY_COMMUNICATION_IP_FIELD`，前面已经进行过默认值设置了
```python
GlobalSettings.get_config(key=GlobalSettings.KeyEnum.PROXY_COMMUNICATION_IP_FIELD.value) or "inner_ip"
```

2022-12-22 07:19 UTC, ZhuoZhuoCrayon commented on apps/node_man/models.py
> +            communication_ip: str = getattr(self, proxy_communication_ip_field)
采用兜底策略获取IP值更合理
```python
communication_ip: str = getattr(self, proxy_communication_ip_field, "") or self.inner_ip
```

场景：比如只有一部分场景需要用到这个特性，`data_ip` 可能是需要使用到了才是有值的，那对于没有值的部分，还是默认用 `inner_ip` 渲染

2022-12-22 07:41 UTC, ZhuoZhuoCrayon commented
已切 base 至 `hotfix/2.1.355`，辛苦重新同步分支代码

2022-12-22 07:46 UTC, ZhuoZhuoCrayon requested changes
补充文档

2022-12-22 12:29 UTC, ladymamawang commented
> 已切 base 至 `hotfix/2.1.355`，辛苦重新同步分支代码

已同步

2022-12-22 12:29 UTC, CohleRustW commented
> 补充文档

已补充

2022-12-23 01:56 UTC, ZhuoZhuoCrayon reviewed
1. 数据 IP 是隐藏字段，并没有相关的渲染逻辑，建议图里改用 `出口 IP` 进行表示
2. 图二的 NAT 是双向的，可以多画个箭头
3. 端口描述：48668 不一定是环境通用的，可以改为 `Agent 通信端口`，17980-Nginx 下载端口，17981-网络代理端口

2022-12-23 01:56 UTC, ZhuoZhuoCrayon commented on docs/solution/solution_cloud_host_communication.md
> +  - 部分企业内网络复杂，需要在云区域主机通信时，并不能根据 Proxy 和 P-Agent 之间的内网进行通信，需要通过公网进行通信
疑似病句：需要在....时，并不能... ｜ 应该是：在....时，并...

2022-12-23 01:56 UTC, ZhuoZhuoCrayon commented on docs/solution/solution_cloud_host_communication.md
> +  - 该场景下，企业使用的是公网 IP 在 CMDB 进行注册，而 Proxy 是使用内网 IP 进行注册，这样就会导致云区域主机通信失败
1. 明确操作对象，P-Agent 使用公网 IP 在 CMDB 注册
2. 没有描述通信失败的原因：Proxy 默认是通过内网和 P-Agent 通信的，但 Proxy 处于「直连区域」，而希望纳入 Proxy 管控的 P-Agent 位于其他云区域，处于不同云区域，无法通过「内网 IP」进行通信

2022-12-23 01:56 UTC, ZhuoZhuoCrayon commented on docs/solution/solution_cloud_host_communication.md
> +  - 为了满足这种需求，需要在云区域主机通信时，增加一个字段，用于指定 Proxy 在节点管理注册的相关 IP 地址，用于与 P-Agent 进行通信
这句话不属于「问题描述」的范畴

2022-12-23 01:56 UTC, ZhuoZhuoCrayon commented on docs/solution/solution_cloud_host_communication.md
> +  - 增加配置 `PROXY_COMMUNICATION_IP_FIELD`, 默认为 `inner_ip`，可指定为 `data_ip`, `login_ip` 等
漏掉了很重要的 `outer_ip`

2022-12-23 01:56 UTC, ZhuoZhuoCrayon commented on docs/solution/solution_cloud_host_communication.md
> +  - 在图二场景下, 在节点管理安装 Proxy 时，可以指定 `数据IP` 为 Proxy 在 NAT 转换后的地址, 并且在节点管理 `admin` 页面
这里有两种 case，需要分别给出方案：
1. 使用 `出口IP`，也就是 `outer_ip`：如果所有的云区域都是通过外网IP/NAT IP 与 P-gent 通信的，那就配置 `outer_ip`
2. 使用 `数据IP`，也就是 `data_ip`：仅部分云区域通过外网IP/ NAT IP 与 P-Agent 通信，通过数据库修改这部分云区域下 Proxy 的 `data_ip`，其他云区域仍使用默认的内网 IP 与 P-Agent 交互

2022-12-23 02:14 UTC, ZhuoZhuoCrayon commented on apps/node_man/models.py
> +        except AttributeError:
有兜底了，就不需要异常捕获了

2022-12-23 02:14 UTC, ZhuoZhuoCrayon commented on apps/node_man/models.py
> +            GlobalSettings.get_config(key=GlobalSettings.KeyEnum.PROXY_COMMUNICATION_IP_FIELD.value) or "inner_ip"
这里应该从 `settings` 里面取值，高频方法，`get_config` 会读数据库

`settings.PROXY_COMMUNICATION_IP_FIELD`

2022-12-23 02:14 UTC, ZhuoZhuoCrayon commented on docs/solution/solution_cloud_host_communication.md
> +全局配置表新增配置 `PROXY_COMMUNICATION_IP_FIELD` 为 `data_ip`，这样就可以实现将 P-Agent 的 `GSE` 相关上游地址配置为 Proxy
新增/修改该配置后，需要重启节点管理服务

2022-12-23 08:07 UTC, ZhuoZhuoCrayon approved these changes
LGTM

2022-12-23 08:08 UTC, merged