feature:  提供创建 GSE 2.0 接入点的命令 (closed #1574)
TencentBlueKing/bk-nodeman pull request #1575
Opened 2023-05-26 10:13 UTC by wyyalt

2023-05-29 12:49 UTC, ZhuoZhuoCrayon requested changes
补充单元测试

2023-05-29 12:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/constants.py
> +        "trunk_port": 48331,
trunk_port / db_proxy_port 这两个 IP 是跟随 `BKAPP_RUN_ENV` 变化的，不能写死

2023-05-29 12:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/management/commands/create_ap_for_gse2.py
> +            gray_ap_map[gse_v1_ap.id] = gse_v2_ap.id
`gse_v1_ap.id` 不先转成 str 的话会不会有问题

2023-05-29 12:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/management/commands/create_ap_for_gse2.py
> +        parser.add_argument(
`name` & `description` 可以忽略，自动加 `GSE2` 的前缀，创建成功后，提示用户可以到页面去改，尽量精简

2023-05-30 10:13 UTC, ZhuoZhuoCrayon commented on apps/node_man/management/commands/create_ap_for_gse2.py
> +        gse_v1_ap: AccessPoint = AccessPoint.objects.filter(id=kwargs["reference_ap_id"]).first()
加个 V2 的搜索条件，避免用户错填 2.0 的接入点

2023-06-02 02:21 UTC, wyyalt commented on apps/node_man/management/commands/create_ap_for_gse2.py
> +        gse_v1_ap: AccessPoint = AccessPoint.objects.filter(id=kwargs["reference_ap_id"]).first()
get_gray_ap_map返回的map的key就是int类型

2023-06-02 02:22 UTC, wyyalt commented on apps/node_man/management/commands/create_ap_for_gse2.py
> +            gray_ap_map[gse_v1_ap.id] = gse_v2_ap.id
不会的

2023-06-02 02:27 UTC, wyyalt commented on apps/node_man/management/commands/create_ap_for_gse2.py
> +        parser.add_argument(
OK

2023-06-02 02:27 UTC, wyyalt commented on apps/node_man/management/commands/create_ap_for_gse2.py
> +        gse_v1_ap: AccessPoint = AccessPoint.objects.filter(id=kwargs["reference_ap_id"]).first()
V1吧

2023-06-05 04:12 UTC, closed without merging