optimization:  支持周期删除订阅执行日志 (closed #1348)
TencentBlueKing/bk-nodeman pull request #1656
Opened 2023-07-09 12:20 UTC by CohleRustW

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +# -*- coding: utf-8 -*-
放到 backend.periodic_tasks 更合适？

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +        models.GlobalSettings.KeyEnum.CLEAN_SUBSCRIPTION_DATA_MAP.value
期望默认开启清理，如果没有配置的话，需要有个默认配置，看起来只要 or {} 就可以，下面有返回默认配置

而且感觉需要有一段注释，描述默认的清理策略是什么

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +    def _build_sub_detail_sql(days: int, limit: int, log_save_levels: Optional[List[str]] = None) -> str:
这两个内置方法可以提出来，提高代码可读性

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +
日志打印下清理参数，便于问题定位排查

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +    job_map_clean_status: List[int] = clean_subscription_data_map.get("job_map_clean_status", [])
默认清理有明确状态的数据，FAILED / SUCCESS 都可以清理

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +    sub_ins_detail_save_log_status: List[str] = clean_subscription_data_map.get("sub_ins_detail_save_log_status", [])
默认保留失败日志

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +    limit: int = clean_subscription_data_map.get("limit", DEFAULT_CLEAN_RECORD_LIMIT)
上次验证过，一次删 5000 没啥问题

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +        if days != 0:
不加时间条件是个伪需求，而且如果真的 day=0，并且 log_save_levels 不为空，下面的 sql 直接语法错误

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +        clean_status_str: str = ", ".join([f"{status}" for status in clean_status])
处理程序输入边界，`clean_status` 为空，应该是表示不带这个条件？

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/clean_subscription_data.py
> +        cursor.execute(sub_detail_delete_sql)
把删除的条数也打成日志

2023-07-17 03:39 UTC, ZhuoZhuoCrayon commented on apps/backend/tests/periodic_tasks/test_clean_subscription_data.py
> +            "job_map_clean_status": self.job_sub_instance_clean_status,
👍 单测很不错

2023-07-19 02:00 UTC, ZhuoZhuoCrayon commented on apps/backend/periodic_tasks/clean_subscription_data.py
> +    enable_clean_subscription_data: bool = clean_subscription_data_map.get("enable_clean_subscription_data", True)
如果 `clean_subscription_data_map` 没有配置，这个逻辑会报错。

所以 `models.GlobalSettings.get_config` get 不到，要提供默认值 `{}`

2023-07-19 02:00 UTC, ZhuoZhuoCrayon commented on apps/backend/periodic_tasks/clean_subscription_data.py
> +    run_every=crontab(hour="1-8", minute="*/5"),
这个可以全天打开，每隔 5 min 清理一波

2023-07-19 02:00 UTC, ZhuoZhuoCrayon commented on apps/backend/periodic_tasks/clean_subscription_data.py
> +        f"rule: {models.GlobalSettings.KeyEnum.CLEAN_SUBSCRIPTION_DATA_MAP.value} -> [{clean_subscription_data_map}]"
应该是打印 `limit` `alive_days` .... 这些具体的变量？默认情况下 `clean_subscription_data_map` 是空字典，打印了也没参考意义

2023-07-19 02:00 UTC, ZhuoZhuoCrayon commented on apps/backend/periodic_tasks/clean_subscription_data.py
> +        appoint_clean_status: Optional[List[int]] = None,
`status` -> `statuses`

2023-07-19 02:00 UTC, ZhuoZhuoCrayon commented on apps/backend/periodic_tasks/clean_subscription_data.py
> +    def build_delete_query_sql(
这个方法为啥不抽出去和 `clean_subscription_data` 并列呢，内置方法共享变量很容易踩坑

2023-07-19 02:00 UTC, ZhuoZhuoCrayon commented on apps/backend/periodic_tasks/clean_subscription_data.py
> +            where_condition: str = f"WHERE status IN ({', '.join([f'{status}' for status in appoint_clean_status])})"
IN 缺了双引号，这段 sql 会报错
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/e0e357dd-840d-48cd-8ef4-cee9ceca50d7)

2023-07-19 02:00 UTC, ZhuoZhuoCrayon commented on apps/backend/tests/periodic_tasks/test_clean_subscription_data.py
> +    def setUpTestData(cls):
这个单测仅在 Class 创建后执行一次，看测试逻辑，每个 test_ 方法执行都需要重新初始化数据，请使用 `setUp`

2023-07-19 02:00 UTC, ZhuoZhuoCrayon commented on apps/backend/tests/periodic_tasks/test_clean_subscription_data.py
> +        GlobalSettings.set_config(GlobalSettings.KeyEnum.CLEAN_SUBSCRIPTION_DATA_MAP.value, sub_clean_map)
断言下执行清理前的数量

2023-07-19 02:02 UTC, ZhuoZhuoCrayon commented
把 clean_pipeline_data 这个周期任务顺便删除哈

2023-07-19 02:05 UTC, ZhuoZhuoCrayon requested changes
真实自测及截图：
1. 使用默认配置，日志打印的 SQL 准确、数据可以正常删除
2. 使用自定义配置（调整 limit，alive_time，sub_ins_detail_save_log_status），日志打印的 SQL 准确，数据可以正常删除

2023-07-19 03:06 UTC, CohleRustW commented on apps/backend/periodic_tasks/clean_subscription_data.py
> +        f"rule: {models.GlobalSettings.KeyEnum.CLEAN_SUBSCRIPTION_DATA_MAP.value} -> [{clean_subscription_data_map}]"
<img width="803" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/40767043/ea7645f4-16a1-4cd1-b297-0071d5393bd9">

补充打印的是这里的 Review 事项

2023-07-25 06:48 UTC, ZhuoZhuoCrayon approved these changes
LGTM

2023-07-25 06:49 UTC, merged