feature:  同步插件进程状态优化 (closed #1887)
TencentBlueKing/bk-nodeman pull request #1895
Opened 2023-10-27 07:36 UTC by Huayeaaa

## PR

### CheckList（PR Assigners）

确认已完成以下操作：

- [ ] 已将分支与当前合入分支同步
- [ ] 已在关联 Issue 中补充「功能自测」部分内容
- [ ] 已更新关联 Issue 的状态 `backlog` -> `todo` -> `for test` -> `tested（需通过测试同学测试）` -> `done`
- [ ] 将 PR 添加上 `pr/reviewable`

### CheckList（PR Reviewers）

确认已完成以下操作：

- [ ] 检查关联 Issue 「功能自测」部分内容
- [ ] 必要时打回 `pr/reviewable`，要求重新修改
- [ ] 及时 Approve

2023-10-27 07:36 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-nodeman?pullRequest=1895) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-nodeman?pullRequest=1895) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-nodeman?pullRequest=1895) it.</sub>

2023-10-27 07:41 UTC, Huayeaaa commented
单个遍历业务所产生的celery任务
![企业微信截图_16983905324622](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/3d4f66f8-2049-44e4-a5cd-036267a07ad1) 
对其进行分片之后所产生的celery任务
![企业微信截图_16983907063758](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/0bdf5cd7-b1ff-4899-8a1d-f3968314ba2d)
此条件下的窗口大小为3用于测试，上线已改成15；通过常量配置文件中的WINDOW_SIZE设置窗口大小；以便后续进行修改
![企业微信截图_1698390823681](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/60e2aae4-b59a-4c79-a62a-5f94be6762fc)
所更改的代码文件进行的文件单测也OK
![企业微信截图_16983909705311](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/6c241104-c8d6-4134-a1de-a361c99122c2)

2023-10-30 02:09 UTC, ZhuoZhuoCrayon requested changes
补充必要单元测试，验证产生的 celery 次数：
1. mock 掉 `query_bk_biz_ids` 方法，返回 2000 个业务
2. 每个业务创建 5000 台主机
3. 断言最终调用 `update_or_create_proc_status` 的次数，该方法也可以 mock

补充 2，创建主机可以使用 `apps.node_man.tests.utils.create_host` 

目标：学习 mock 使用

2023-11-01 02:13 UTC, CohleRustW commented on apps/node_man/periodic_tasks/sync_proc_status_task.py
> +        # host_queryset = Host.objects.filter(bk_biz_id=bk_biz_id)
注释的代码信息提交时要删掉

2023-11-01 02:25 UTC, CohleRustW commented on apps/node_man/periodic_tasks/sync_proc_status_task.py
> +    for bk_biz_id_list in list(chunk_lists(bk_biz_ids, constants.WINDOW_SIZE)):
WINDOWS_SIZE 这个命名可能不够清晰

2023-11-03 02:03 UTC, ZhuoZhuoCrayon commented on .gitignore
> +.codecc
PyCharm ChangeList 支持分区，把这类本地配置单独放到一个 Tab，避免提交
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/4f9e3828-d32c-4840-9cf9-4aee2c10a69f)

2023-11-03 02:03 UTC, ZhuoZhuoCrayon commented on apps/node_man/constants.py
> +BIZ_SHARDING_SIZE = 15
可以考虑下常量名带上「场景」的前缀，比如：`QUERY_PROC_STATUS_BIZ_SHARDING_SIZE`

2023-11-03 02:03 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/sync_proc_status_task.py
> +                f"{task_id} | sync_proc_status_task: bk_biz_id -> {bk_biz_id_list}, host_count -> {count}, skip"
`bk_biz_id_list -> {bk_biz_id_list}`

2023-11-03 02:03 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/sync_proc_status_task.py
> +            f"{task_id} | sync_proc_status_task: start to sync bk_biz_id -> {bk_biz_id_list}, host_count -> {count}"
`bk_biz_id_list -> {bk_biz_id_list}`

2023-11-03 02:03 UTC, ZhuoZhuoCrayon commented on apps/node_man/periodic_tasks/sync_proc_status_task.py
> +                f"{task_id} | sync_proc_status_task: bk_biz_id -> {bk_biz_id_list}, sync after {countdown} seconds"
`bk_biz_id_list -> {bk_biz_id_list}`

2023-11-03 02:03 UTC, ZhuoZhuoCrayon commented on apps/node_man/tests/test_pericdic_tasks/test_sync_proc_status_task.py
> +        for host in host_queryset:
这里想实现的是，每 25 台机器更新一次业务 ID，感觉通过获取全部的主机 ID - `all_host_ids`，然后通过 chunk_lists 分批更新实现，代码更简洁

2023-11-06 01:57 UTC, ZhuoZhuoCrayon approved these changes
LGTM

2023-11-06 01:58 UTC, merged