optimization:  灰度回滚逻辑优化 (closed #1893)
TencentBlueKing/bk-nodeman pull request #1897
Opened 2023-10-27 10:02 UTC by wyyalt

## PR

### CheckList（PR Assigners）

确认已完成以下操作：

- [ ] 已将分支与当前合入分支同步
- [ ] 已在关联 Issue 中补充「功能自测」部分内容
- [ ] 已更新关联 Issue 的状态 `backlog` -> `todo` -> `for test` -> `tested（需通过测试同学测试）` -> `done`
- [ ] 将 PR 添加上 `pr/reviewable`

### CheckList（PR Reviewers）

确认已完成以下操作：

- [ ] 检查关联 Issue 「功能自测」部分内容
- [ ] 必要时打回 `pr/reviewable`，要求重新修改
- [ ] 及时 Approve

2023-10-29 07:30 UTC, ZhuoZhuoCrayon commented on apps/core/gray/handlers.py
> +            cls.update_cloud_ap_id(validated_data, rollback=True)
这个要怎么理解：确保业务移除灰度列表前能正常判定管控区域所属关系？
这里想到两个问题：
1. 如果多业务传入，并且只回滚一个 IP，这里的逻辑会将 IP 所属业务外的其他传入业务的管控区域也回滚成 V1
2. 单业务，指定 IP，不属于该 IP 的其他管控区域也全部回滚

所以这里是不是仅回滚主机所属的管控区域更合适？

2023-10-30 07:48 UTC, wyyalt commented on apps/core/gray/handlers.py
> +            cls.update_cloud_ap_id(validated_data, rollback=True)
回滚管控区域需要使用业务作为搜索条件，所以需要先回滚管控区域<img width="829" alt="image" src="https://github.com/TencentBlueKing/bk-nodeman/assets/26807891/f5224c56-86c0-4b06-acca-761921d74b3d">

2023-10-31 01:18 UTC, ZhuoZhuoCrayon requested changes
提升单测覆盖度

2023-10-31 01:18 UTC, ZhuoZhuoCrayon commented on apps/core/gray/handlers.py
> +        clouds: typing.List[int] = [],
Python 更推荐的写法是 `clouds: typing.Optional[typing.List[int]]  = None`，在代码里 `clouds = clouds or []`

2023-10-31 01:18 UTC, ZhuoZhuoCrayon commented on apps/core/gray/handlers.py
> +        clouds: typing.List[int] = clouds or list(
变量命名规范：用 `cloud_ids` 等带有 `ID` 的命名是不是更好一点

2023-10-31 01:18 UTC, ZhuoZhuoCrayon commented on apps/core/gray/handlers.py
> +                rollback_info: typing.List[typing.Dict[str, int]] = list(
建议：表示回滚主机列表，用 `rollback_host_infos` 等带有 `host` 的命名

2023-10-31 01:18 UTC, ZhuoZhuoCrayon commented on apps/core/gray/handlers.py
> +                need_update_host_id: typing.List[int] = list(set(partial_host_ids) - set(gse_v1_ap_id_is_none_host_ids))
`need_update_host_ids`

2023-11-01 01:41 UTC, ZhuoZhuoCrayon commented on apps/core/gray/handlers.py
> +        clouds: typing.Optional[typing.List[int]] = None,
`cloud_ids`

2023-11-01 01:41 UTC, ZhuoZhuoCrayon commented on apps/core/gray/handlers.py
> +                # 如果按业务回滚在上层已进行了回滚，此处不做处理
if 分支内补充必要日志，便于后续排查问题

2023-11-10 07:53 UTC, ZhuoZhuoCrayon approved these changes
LGTM

2023-11-10 07:53 UTC, merged