feature:  安装通道支持隐藏功能 (closed #1832)
TencentBlueKing/bk-nodeman pull request #1902
Opened 2023-10-30 09:12 UTC by CohleRustW

## PR

### CheckList（PR Assigners）

确认已完成以下操作：

- [ ] 已将分支与当前合入分支同步
- [ ] 已在关联 Issue 中补充「功能自测」部分内容
- [ ] 已更新关联 Issue 的状态 `backlog` -> `todo` -> `for test` -> `tested（需通过测试同学测试）` -> `done`
- [ ] 将 PR 添加上 `pr/reviewable`

### CheckList（PR Reviewers）

确认已完成以下操作：

- [ ] 检查关联 Issue 「功能自测」部分内容
- [ ] 必要时打回 `pr/reviewable`，要求重新修改
- [ ] 及时 Approve

2023-11-08 01:41 UTC, ZhuoZhuoCrayon requested changes
没啥问题，辛苦修改合入目标分支

2023-11-08 01:41 UTC, ZhuoZhuoCrayon commented on apps/node_man/views/install_channel.py
> +        is_hidden: bool = str(hidden).lower() in ["false", "0"]
看看是不是可以复用这个方法：apps/utils/string.py str2bool

2023-11-08 09:29 UTC, CohleRustW commented on apps/node_man/views/install_channel.py
> +        is_hidden: bool = str(hidden).lower() in ["false", "0"]
换了～

2023-11-08 09:29 UTC, CohleRustW commented
> 没啥问题，辛苦修改合入目标分支

已处理

2023-11-09 01:25 UTC, ZhuoZhuoCrayon approved these changes

2023-11-09 01:25 UTC, merged