optimization:  任务历史搜索优化 (closed #1856)
TencentBlueKing/bk-nodeman pull request #1915
Opened 2023-11-03 03:33 UTC by ping15

## PR

### CheckList（PR Assigners）

确认已完成以下操作：

- [ ] 已将分支与当前合入分支同步
- [ ] 已在关联 Issue 中补充「功能自测」部分内容
- [ ] 已更新关联 Issue 的状态 `backlog` -> `todo` -> `for test` -> `tested（需通过测试同学测试）` -> `done`
- [ ] 将 PR 添加上 `pr/reviewable`

### CheckList（PR Reviewers）

确认已完成以下操作：

- [ ] 检查关联 Issue 「功能自测」部分内容
- [ ] 必要时打回 `pr/reviewable`，要求重新修改
- [ ] 及时 Approve

2023-11-03 06:19 UTC, ping15 commented
## 自测
1. filter_condition测试
#### 不带bk_biz_scope(即用户全部业务，使用admin测试)
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/3ed8f5e8-7608-4cce-8e5f-fb43f8c33377)
#### 单业务
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/fdad033e-4573-4181-85de-549f914c4028)
#### 中间数量业务
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/ff626c61-ddd8-4918-b26f-ec906ad11892)
#### 全业务
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/077e70c4-01a0-49d1-ab88-a5dba571bab6)
#### 带时间过滤
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/0c57651e-bc63-4518-9c78-772fe27bbf42)
2. job_list测试
#### 单业务
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/cd2c6bcb-0557-4bb5-861b-563562121690)
#### 中间业务
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/54f005e5-386f-447d-881a-16bb652c8889)
#### 全业务
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/76253681/61adb269-1d4b-4ccb-9f99-fa32f8ba0469)

2023-11-06 01:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/serializers/meta.py
> +    bk_biz_ids = serializers.ListField(label=_("业务列表"), required=False, default=[])
指定 `child`

2023-11-06 01:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/tests/test_handlers/test_meta.py
> +    def fetch_Job_unique_col_count(self, search_business=None):
命名规范：`Job` -> `job`

2023-11-06 01:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/tools/job.py
> +        :param all_biz_info: 所有的业务id
这里似乎也是 dict？

2023-11-06 01:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/tools/job.py
> +            biz_scope = [bk_biz_id for bk_biz_id in search_biz_ids if bk_biz_id in biz_info]
等价操作：set(biz_permission) & set(search_biz_id)

2023-11-06 01:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/tools/job.py
> +                operator.and_, [Q(bk_biz_scope__contains=bk_biz_id) for bk_biz_id in biz_scope], Q()
`not A and not B and not C` =  `not (A or B or C)`

2023-11-06 01:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/tests/test_handlers/test_meta.py
> +            {
似乎没有配置 `pre-commit` ?

2023-11-06 01:49 UTC, ZhuoZhuoCrayon commented on apps/node_man/tests/test_handlers/test_meta.py
> +        ])
可以再补充一个单元测试，验证取反的场景

2023-11-13 02:13 UTC, ZhuoZhuoCrayon commented on apps/node_man/tools/job.py
> +            # 字典的 in 比列表性能更高
这个注释似乎和代码没啥关系

2023-11-13 02:13 UTC, ZhuoZhuoCrayon commented on apps/node_man/tools/job.py
> +        if not biz_scope:
函数一般遵循单一返回值的原则，这里抛一个 ValueError 供上层捕获是不是更好一些

2023-11-17 14:35 UTC, ZhuoZhuoCrayon requested changes

2023-11-17 14:35 UTC, ZhuoZhuoCrayon commented on apps/node_man/tests/test_handlers/test_meta.py
> +            if any(biz_id in {biz["bk_biz_id"] for biz in search_business} for biz_id in set(job["bk_biz_scope"])):
虽然是测试代码，但最好把一些公共变量放到 for 循环外面，避免占用内存
1. `set(job["bk_biz_scope"])`
2. `{biz["bk_biz_id"] for biz in search_business}`

2023-11-20 01:41 UTC, ZhuoZhuoCrayon approved these changes
LGTM

2023-11-20 01:41 UTC, merged