feature:   支持「BT传输」「数据压缩」「管控区域:IP」筛选 (closed #1770)
TencentBlueKing/bk-nodeman pull request #1952
Opened 2023-11-16 02:46 UTC by Huayeaaa

## PR

### CheckList（PR Assigners）

确认已完成以下操作：

- [ ] 已将分支与当前合入分支同步
- [ ] 已在关联 Issue 中补充「功能自测」部分内容
- [ ] 已更新关联 Issue 的状态 `backlog` -> `todo` -> `for test` -> `tested（需通过测试同学测试）` -> `done`
- [ ] 将 PR 添加上 `pr/reviewable`

### CheckList（PR Reviewers）

确认已完成以下操作：

- [ ] 检查关联 Issue 「功能自测」部分内容
- [ ] 必要时打回 `pr/reviewable`，要求重新修改
- [ ] 及时 Approve

2023-11-16 02:51 UTC, Huayeaaa commented
对于所补单测位置进行整个文件测试OK
![企业微信截图_17001022672305](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/8f765648-ac16-4bb3-a893-f13163411902)

2023-11-16 08:16 UTC, Huayeaaa commented
对于所补单测位置进行整个文件测试OK
![企业微信截图_17001213445701](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/5d04e4d1-5cb4-473d-8abf-8566a62729d4)

![企业微信截图_17001183871556](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/5e321cae-a8a2-4705-846c-e35888812af8)

2023-11-16 09:51 UTC, GONGONGONG commented
前端测试
IPV4-通过&不通过
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/51b241bf-01a7-4004-a9a8-de0d2f4ddbd5)
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/f307ab44-31e4-4c29-b129-34cc057c9fae)

IPV6-通过&不通过
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/c421c2e7-b750-4fa1-9f0c-f52ee23a6444)
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/29882448/c97311e3-9c36-495a-97d5-37837f05cd1f)

2023-11-17 14:22 UTC, ZhuoZhuoCrayon requested changes

2023-11-17 14:22 UTC, ZhuoZhuoCrayon commented on apps/core/ipchooser/tools/base.py
> +            filter_q &= Q(extra_data__peer_exchange_switch_for_agent=condition_value) | Q(extra_data={})
如果 `extra_data` 是空，认为 BT 传输「未启用」

2023-11-17 14:22 UTC, ZhuoZhuoCrayon commented on apps/core/ipchooser/tools/base.py
> +    if len(condition_values) > 1:
1. `condition_values` 可以做下去重，避免 `[0, 0, 0]` 这种情况的传入
2. 如果 > 1，对于 bool 值来说，应该是等同于「全选」？这里是不是可以直接去掉筛选逻辑了

2023-11-17 14:22 UTC, ZhuoZhuoCrayon commented on apps/core/ipchooser/tools/base.py
> +            filter_q &= Q(bk_cloud_id__in=bk_cloud_id_set) & Q(inner_ip__in=ipv4s) | Q(inner_ipv6__in=ipv6s)
1. for 循环里 `&`，感觉这个地方会有问题：[ip1], [ip1, ip2], [ip1, ip2...ipn]
2. 如果查的 IP 特别多，这里可能会有 SQL 超长的问题；而且这里有 BUG，试试搜 `1:127.0.0.1\n2:127.0.0.2` 会不会把 `2:127.0.0.1` `1:127.0.0.2` 搜出来
3. 参考下这段逻辑（apps.core.ipchooser.tools.base.HostQueryHelper.or_query_hosts）看看，区别是我们需要用 and，而不是 or
![企业微信截图_dff6d2db-f7bf-48af-9dc2-c78476e9a18f](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/71d3fe13-0e46-496f-b2a1-88ec886237cc)

2023-11-17 14:22 UTC, ZhuoZhuoCrayon commented on apps/core/ipchooser/tools/base.py
> +                filter_q = handle_ip_search(condition["value"], filter_q)
👍 很优雅的提取方式

2023-11-17 14:22 UTC, ZhuoZhuoCrayon commented on apps/node_man/handlers/meta.py
> +            {"name": _("管控区域:IP"), "id": "bk_cloud_ip"},
文案改下：管控区域ID:IP

2023-11-17 14:22 UTC, ZhuoZhuoCrayon commented on apps/node_man/handlers/meta.py
> +        ret_value.append({"name": _("管控区域:IP"), "id": "bk_cloud_ip"})
文案改下：管控区域ID:IP

2023-11-17 14:22 UTC, ZhuoZhuoCrayon commented on apps/node_man/handlers/meta.py
> +        if not settings.BKAPP_ENABLE_DHCP:
条件反了，「数据压缩」是 Agent 2.0 的新特性，ENABLE 的时候展示

2023-11-17 14:22 UTC, ZhuoZhuoCrayon commented on apps/node_man/tests/test_handlers/test_host.py
> +    # 测试管控区域:IP、version、IP查询; 因创建主机的IP具有随机性，无法进行准确校验，以空数据作为校验的标准
1. 试试在单元测试里面，把若干主机的 IP、管控区域改成自己需要的值，再去检索
2. 测试添加刚刚说的搜索 `1:127.0.0.1` `2:127.0.0.2` 的场景（核心是不同 IP、管控区域排列组合）

2023-11-22 08:12 UTC, ZhuoZhuoCrayon approved these changes
LGTM

2023-11-22 08:12 UTC, merged