feature:  针对禁用业务创建订阅的逻辑优化 (closed #1934)
TencentBlueKing/bk-nodeman pull request #1958
Opened 2023-11-17 04:59 UTC by CohleRustW

## PR

### CheckList（PR Assigners）

确认已完成以下操作：

- [ ] 已将分支与当前合入分支同步
- [ ] 已在关联 Issue 中补充「功能自测」部分内容
- [ ] 已更新关联 Issue 的状态 `backlog` -> `todo` -> `for test` -> `tested（需通过测试同学测试）` -> `done`
- [ ] 将 PR 添加上 `pr/reviewable`

### CheckList（PR Reviewers）

确认已完成以下操作：

- [ ] 检查关联 Issue 「功能自测」部分内容
- [ ] 必要时打回 `pr/reviewable`，要求重新修改
- [ ] 及时 Approve

2023-11-20 02:03 UTC, ZhuoZhuoCrayon requested changes

2023-11-20 02:03 UTC, ZhuoZhuoCrayon commented on apps/backend/subscription/tools.py
> +def check_sub_scope_biz_is_disabled(
为什么要单独拎出来一个方法，不能复用 `check_subscription_is_disabled` ?

2023-11-20 02:03 UTC, ZhuoZhuoCrayon commented on apps/backend/subscription/serializers.py
> +        if check_sub_scope_biz_is_disabled(scope=attrs["scope"], nodes=attrs["scope"]["nodes"]):
1. 期望是「非插件类任务不进行禁用」，这里则会把所有任务都禁用
2. 订阅更新也需要在「保存」订阅之前，抛出异常「核心问题是，节点管理保存的订阅，但在执行前报错了，期望调整为保存前报错」
3. 之前 handler 已经有相关的 check 逻辑，似乎只需要调整下原先的代码位置？
![企业微信截图_1e5b867a-ceae-430d-9f3c-0f22f69b8996](https://github.com/TencentBlueKing/bk-nodeman/assets/42019787/99cea697-d542-4169-bb88-6f2cc2968ee8)

2023-11-20 02:03 UTC, ZhuoZhuoCrayon commented on apps/backend/subscription/tools.py
> +    nodes: typing.List[typing.Dict[str, Any]],
scope 包含了 nodes，这里的参数设置有点冗余

2023-11-22 03:51 UTC, ZhuoZhuoCrayon commented on apps/backend/subscription/tools.py
> +    subscription_info: typing.Dict[str, typing.Any],
这个参数有点冗余，感觉传进来只是为了打印日志，可以考虑改为传入 `subscription_identity(str)`，对于更新场景，在外层 str(subscription) 就能通过 Model 的 `__str__` 方法获取订阅标识，对于创建的场景，随便拼一个能代表当前订阅的信息就可

2023-11-22 03:51 UTC, ZhuoZhuoCrayon commented on apps/backend/subscription/tools.py
> +            set(scope.get("bk_biz_scope") or []) & set(disable_biz_ids),
scope 里没有 `bk_biz_scope`，不过这个条件可以去掉，策略场景用 `nodes_biz_ids` 也可以判断出来

2023-11-22 03:51 UTC, ZhuoZhuoCrayon commented on apps/backend/subscription/tools.py
> +    nodes_biz_ids: typing.Optional[typing.List[int]] = [node.get("bk_biz_id") for node in nodes]
应该是 `typing.List[typing.Optional[int]]` ? （不过为啥不把 None 过滤掉

2023-11-22 03:51 UTC, ZhuoZhuoCrayon commented on apps/backend/subscription/tools.py
> +    full_biz_scope_ids: typing.Optional[typing.List[int]] = [
同

2023-11-24 09:30 UTC, CohleRustW commented on apps/backend/subscription/tools.py
> +    nodes_biz_ids: typing.Optional[typing.List[int]] = [node.get("bk_biz_id") for node in nodes]
已过滤

2023-11-24 09:30 UTC, CohleRustW commented on apps/backend/subscription/tools.py
> +    full_biz_scope_ids: typing.Optional[typing.List[int]] = [
处理了

2023-11-24 09:30 UTC, CohleRustW commented on apps/backend/subscription/tools.py
> +            set(scope.get("bk_biz_scope") or []) & set(disable_biz_ids),
删掉这个条件了

2023-11-24 09:31 UTC, CohleRustW commented on apps/backend/subscription/tools.py
> +    subscription_info: typing.Dict[str, typing.Any],
直接打了订阅 ID 在日志，简化传参

2023-11-28 03:48 UTC, ZhuoZhuoCrayon approved these changes
LGTM

2023-11-28 03:48 UTC, merged