feat：已停用插件禁止被安装
TencentBlueKing/bk-nodeman pull request #2135
Opened 2024-03-19 03:45 UTC by Huayeaaa

, # Reviewed, transaction id: 4088

## PR

### CheckList（PR Assigners）

确认已完成以下操作：

- [ ] 已将分支与当前合入分支同步
- [ ] 已在关联 Issue 中补充「功能自测」部分内容
- [ ] 已更新关联 Issue 的状态 `backlog` -> `todo` -> `for test` -> `tested（需通过测试同学测试）` -> `done`
- [ ] 将 PR 添加上 `pr/reviewable`

### CheckList（PR Reviewers）

确认已完成以下操作：

- [ ] 检查关联 Issue 「功能自测」部分内容
- [ ] 必要时打回 `pr/reviewable`，要求重新修改
- [ ] 及时 Approve

2024-03-19 04:18 UTC, Huayeaaa commented
### 单测
![企业微信截图_17108197275416](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/df13ed4e-6553-41eb-9dda-6516bc32a677)

2024-03-25 03:48 UTC, ZhuoZhuoCrayon requested changes
补充功能自测

2024-03-25 03:48 UTC, ZhuoZhuoCrayon commented on apps/node_man/serializers/plugin.py
> +            if GlobalSettings.get_config(key=GlobalSettings.KeyEnum.DISABLE_STOPPED_PLUGIN.value, default=True):
先用 `False`，禁用需要公告

2024-03-25 08:15 UTC, Huayeaaa commented
## 功能自测
### 1.通过标准运维发起插件安装任务（插件已被禁用的情况）
![企业微信截图_17113535778442](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/0a43f83d-6148-43f9-b3cb-9323e329bff0)
仍然可以安装已禁用的插件
![image](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/705c1b2e-17fe-48f9-8bdd-3ded5c200244)

### 2.通过标准运维发起插件安装任务（插件已被禁用且开通全局开关的情况）
![企业微信截图_17113539854343](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/fb5edee4-20a0-47a9-b60c-81425076fc2b)

![企业微信截图_17113541027739](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/7c742421-2255-4941-b972-e0504a0709bb)
![企业微信截图_17113541256299](https://github.com/TencentBlueKing/bk-nodeman/assets/100522884/4cbc62d9-5d47-439f-beea-ae609e8c1cfa)
**禁用规则生效**

2024-03-25 08:51 UTC, ZhuoZhuoCrayon approved these changes
LGTM

2024-03-25 08:51 UTC, merged